### Post a new student.
POST http://localhost:8080/student
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Joe",
  "email": "tylerpiercey@email.com",
  "address": "29 fake road",
  "city": "town",
  "postal": "A0B 1C2",
  "phone": "7097775555"
}

### Post a new course.
POST http://localhost:8080/course
Content-Type: application/json

{
  "courseName": "language",
  "courseNumber": "1",
  "capacity": 100,
  "year": 2020,
  "semester": 3,
  "pid": 40
}

### Get all students
GET http://localhost:8080/student

### Get all courses
GET http://localhost:8080/course

### Get a single student by ID.
GET http://localhost:8080/student/20

### Get a single course by ID.
GET http://localhost:8080/course/4

### Post a new program
POST http://localhost:8080/program
Content-Type: application/json

{
  "programName": "Applied Physics",
  "campus": "Main Campus"
}

### Get all programs
GET http://localhost:8080/program

### Get a single program by ID. Change id number to get different results
GET http://localhost:8080/program/6

### Post a new enrollment
POST http://localhost:8080/enrollment
Content-Type: application/json

{
  "courseId": 1,
  "studentId": 1
}

### Get all enrollments for a course
GET http://localhost:8080/enrollment/course/1

### Get all enrollments for a student
GET http://localhost:8080/enrollment/student/1

### Post a new grade
POST http://localhost:8080/grades
Content-Type: application/json

{
  "studentId": 1,
  "courseId": 1,
  "grade": "A"
}

### Get all grades for a student
GET http://localhost:8080/grades/student/2

### Get all grades for a course
GET http://localhost:8080/grades/course/1

### Modify a student record
PUT http://localhost:8080/student/1
Content-Type: application/json

{
  "firstName": "tyler",
  "lastName": "piercey",
  "email": "tylerpiercey@email.com",
  "address": "29 fake road",
  "city": "town",
  "postal": "A0B 1C2",
  "phone": "7097775555"
}

### Delete a student record
DELETE http://localhost:8080/student/1

### Modify a course
PUT http://localhost:8080/course/1
Content-Type: application/json

{
  "courseName": "language",
  "courseNumber": "1",
  "capacity": 100,
  "year": 2020,
  "semester": 3,
  "pid": 1
}

### Delete a course
DELETE http://localhost:8080/course/1

### Modify a program
PUT http://localhost:8080/program/1
Content-Type: application/json

{
  "programName": "language",
  "campus": "CNA"
}

### Delete a program
DELETE http://localhost:8080/program/1

### Modify an enrollment
PUT http://localhost:8080/enrollment/1
Content-Type: application/json

{
  "courseId": 2,
  "studentId": 3
}

### Delete an enrollment
DELETE http://localhost:8080/enrollment/3

### Modify a grade
PUT http://localhost:8080/grades/1
Content-Type: application/json

{
  "studentId": 1,
  "courseId": 2,
  "grade": "B"
}

### Delete a grade
DELETE http://localhost:8080/grades/1
